Repository openfga/terraform-provider-openfga, pull requests merged in 2025-05, with the labels that each got.

#38 chore(deps): bumped terraform-plugin-* and openfga versions
  go.mod
  go.sum
Labels: chore, deps

#37 chore(license): updated license to apache 2.0
  LICENSE
Labels: chore, license

#40 chore: added readme
  README.md
Labels: chore

#43 ci: pinned all GitHub action versions
  .github/workflows/pr.yml
  .github/workflows/test.yml
Labels: CI/CD

#46 chore: add notice file for compliance
  NOTICE.txt
Labels: chore
